version: '3'
services:
  my-postgres:
    container_name: my-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=resume
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always

  app:
    restart: always
    build: ./
    working_dir: /app
    volumes:
      - ./:/app
      - /temp:/temp
      - ~/.m2:/root/.m2
    ports:
      - "80:8080"
    expose:
      - "80"
    command: mvn -Pdocker clean spring-boot:run
    depends_on:
      - my-postgres
