joinfaces:
  primefaces:
    theme: vela
  faces:
    project-stage: Production
    facelets-libraries: /tags/tags.taglib.xml
tomcat:
  version: @tomcat.version@
jetty:
  version: @jetty.version@
undertow:
  version: @undertow.version@
application-users:
  users-credentials:
    - username: persapiens
      password: 123
      authorities: ADMIN
    - username: nyilmaz
      password: qwe
      authorities: USER
spring:
  datasource:
    url: @spring.datasource.url@
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      platform: postgre
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  web:
    locale: fr_FR

  application:
    admin:
      enabled: true
